#!/bin/bash


sudo wget https://dl.grafana.com/grafana-enterprise/release/12.3.1/grafana-enterprise_12.3.1_20271043721_linux_amd64.tar.gz

sudo tar -zxvf grafana-enterprise_12.3.1_20271043721_linux_amd64.tar.gz


sudo useradd --system --no-create-home --shell /usr/sbin/nologin grafana


sudo mv grafana-12.3.1 /opt/grafana



sudo mkdir -p \
  /var/lib/grafana \
  /var/log/grafana \
  /etc/grafana/provisioning

sudo chown -R grafana:grafana \
  /var/lib/grafana \
  /var/log/grafana \
  /etc/grafana


sudo cp /opt/grafana/conf/defaults.ini /etc/grafana/grafana.ini


sudo tee /etc/systemd/system/grafana.service <<EOF
[Unit]
Description=Grafana Server (Binary)
Documentation=https://grafana.com/docs/
Wants=network-online.target
After=network-online.target

[Service]
User=grafana
Group=grafana
Type=simple

ExecStart=/opt/grafana/bin/grafana-server \
  --homepath=/opt/grafana \
  --config=/etc/grafana/grafana.ini \
  cfg:default.paths.data=/var/lib/grafana \
  cfg:default.paths.logs=/var/log/grafana \
  cfg:default.paths.plugins=/var/lib/grafana/plugins \
  cfg:default.paths.provisioning=/etc/grafana/provisioning

Restart=on-failure
RestartSec=5
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reexec
sudo systemctl daemon-reload

sudo systemctl enable grafana
sudo systemctl start grafana

sudo systemctl status grafana

#journalctl -u grafana -f
#tail -f /var/log/grafana/grafana.log


