#!/bin/bash 


CURRENT_USER=$(id -un)



# 환경 변수

DOCKER_GPG_ASC_URL="https://download.docker.com/linux/ubuntu/gpg"

DOCKER_KEYRING="/usr/share/keyrings/docker-archive-keyring.gpg"

DOCKER_LIST="/etc/apt/sources.list.d/docker.list"


# 필수 패키지 설치

sudo apt update && sudo apt install -y curl gnupg lsb-release



# GPG 키 다운로드 및 변환

sudo curl -fsSL $DOCKER_GPG_ASC_URL -o docker.asc

sudo gpg --dearmor -o $DOCKER_KEYRING docker.asc

rm docker.asc


# Docker 저장소 추가

echo "deb [arch=$(dpkg --print-architecture) signed-by=$DOCKER_KEYRING] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee $DOCKER_LIST > /dev/null


# 패키지 목록 업데이트 및 Docker 설치

sudo apt update

sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


# 설치 확인

docker --version
sudo usermod -aG docker $CURRENT_USER
newgrp docker
echo "Docker 설치 완료!"
