#!/bin/bash 


sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl gpg


sudo mkdir -p /etc/apt/keyrings

curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key \
 | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg


sudo tee /etc/apt/sources.list.d/kubernetes.list <<EOF
deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /
EOF

sudo apt update
sudo apt install -y kubectl

kubectl version --client


sudo mkdir -p ~/.kube
sudo touch  ~/.kube/config

